#!/usr/bin/env php
<?php
/**
 * 命令入口文件,不允许在该文件添加或者修改任何代码
 * @author Gene <https://github.com/Talkyunyun>
 */

// 加载启动配置脚本
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require_once __DIR__ . '/config/console.php';
$application = new yii\console\Application($config);

exit($application->run());