<?php

namespace app\controllers;

use PHPUnit\Framework\Error\Error;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller {


    public $msg = [
        'code' => 0,
        'msg'  => '操作成功',
        'data' => []
    ];

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if (!Yii::$app->user->isGuest) {
//                                $this->user_id = Yii::$app->session->get('user_id');
//                                $this->login_name = Yii::$app->session->get('login_name');
//                                $this->real_name = Yii::$app->session->get('real_name');
                                return true;
                            }else{
                                return false;
                            }
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    if(Yii::$app->user->isGuest){
                        return $this->redirect('/login');
                    }

                }
            ],
        ];
    }

    public function isOffline($action)
    {
        return false;
    }

    public function init()
    {
        error_reporting(E_ERROR);

        parent::init(); // TODO: Change the autogenerated stub
//        $this->layout = "@app/views/layouts/admin";
    }



    protected function sendError($code = 404, $msg = 'Not found Page') {
        return ['code' => $code, 'msg' => $msg];
    }



    /**
     * 定义返回统一格式的json
     * @param string $msg
     * @param int $code
     * @param array $data
     * @return array
     */
    protected function sendRes($msg = 'Not Found Page', $data = [], $code = 1001) {
        return [
            'code' => $code,
            'msg'  => $msg,
            'data' => $data
        ];
    }
}